---
title: "Assignment 1"
format: pdf
editor: visual
---

## 2. LaTeX

(a) $E(Y) = y_1 p_1 + ... + y_k p_k = \sum_{i=1}^k y_i p_i$

(b) $\sigma_y = Var(Y) = E[(Y-\mu_y)^2] = \sum_{i=1}^k (y_i - \mu_y)^2 p_i$

(c) $\hat{\beta} = \frac{\sum_{i=1}^n (y-y_i)(x-x_i)}{\sum_{i-1}^n (x-x_i)^2}$

(d) $P(a \leq Y \leq b) = \int_{a}^{b} f_y (y)dy$

(e) $\hat{g}(x) = \frac{\frac{1}{nh} \sum_{i=1}^n y_ik(\frac{x_i-x}{n})}{\frac{1}{nh} \sum_{i=1}^n k(\frac{x_i-x}{n})}$

## 3.1 R

(a) 

```{r}
n <- 1000 

```

(b) 

```{r}
u_1 <- runif(500,0,1)
u_2 <- runif(500,0,1)

```

(c) 

```{r}
z_1 <- sqrt(-2 * log(u_1)) * cos(2 * pi * u_2)

z_2 <- sqrt(-2 * log(u_1)) * sin(2 * pi * u_2)

```

(d) 

```{r}
z <- c(z_1, z_2)

```

(e) 

```{r}
mu <- 5
sigma <- 2

```

(f) 

```{r}
x <- mu + sigma * z

```

(g) 

```{r}
mean(x)
sd(x)

```

(h) 

```{r}
hist(x,
     freq = FALSE,
     ylab = "Density",
     xlab = "$x$")
curve(dnorm(x, mean = mu, sd = sigma),
      col = "red", lwd = 2, add = TRUE)
```

## 3.2 data frames & indexing

(a) missing values from "Hospital"

```{r}
cihi <- read.csv("hlthexp.csv")

df <- data.frame(Year = cihi$Year,
                 Hospitals = cihi$Hospitals,
                 Physicians = cihi$Physicians,
                 "Other Services" = cihi$Other.Institutions,
                 Dental = cihi$Other.Professionals..Dental.Services,
                 Vision = cihi$Other.Professionals..Vision.Care.Services,
                 "Other Professionals" = cihi$Other.Professionals..Other.Services,
                 check.names = FALSE)

```

(b) 

```{r}
df$TotalOtherServices <- df$Dental + df$Vision + df$"Other Professionals"
```

(d) 

```{r}
df<-data.frame(df,PrescriptionDrugs = cihi$Prescribed.Drugs)
```

(e) 

```{r}
df$Hospitals[df$Year == 1983]
```

(f) 

```{r}
data.frame(df$Year[df$Year>= 2012], df$Hospitals[df$Year>= 2012])
```

## 3.3 other useful R commands

```{r}
#install.packages("ggplot2")
#library(ggplot2)

```

(a) 

```{r}
mpg <- ggplot2::mpg
mpg_subset <- subset(mpg, year == 2008)
min_mpg <- min(mpg_subset$cty)
max_mpg <- max(mpg_subset$cty)
```

(b) 

```{r}
n <- length(mpg_subset$cty)
avg_mpg <- sum(mpg_subset$cty) / n
```



(c) 

```{r}
avg_mpg_mean <- mean(mpg_subset$cty)
```

(d) 

```{r}
compact <- ifelse(mpg$class == "compact", 1, 0)
```


(e)
```{r}
avg_mpg_compact <- mean(compact)
```

(f)
```{r}
#| label: fig-mpg
#| fig-cap: "City Versus Highway Fuel Efficiency (MPG)"
x <- 1:10
y <- x^2
plot(mpg$cty, mpg$hwy, xlab = "City MPG", ylab = "Highway MPG", col = "blue")

```

@fig-mpg shows the fuel eﬀiciency for city driving versus highway driving”.


